<?php

/**
 * @file
 * Provides image search for the USA Search module.
 */

/**
 * Implements hook_search_info().
 */
function usasearch_images_search_info() {
  return array(
    'title' => 'Images',
    'path' => 'images',
    'conditions_callback' => 'usasearch_api_conditions',
  );
}

/**
 * Implements hook_search_execute().
 */
function usasearch_images_search_execute($keys = NULL, $conditions = array()) {
  module_load_include('inc', 'usasearch_api');
  $conditions['index'] = 'images';
  $module = 'usasearch_images';
  $results = usasearch_api_get_results($keys, $conditions, $module);

  return $results;
}

/**
 * Converts a USA Search result to a Drupal search result for images index.
 *
 * @param array $result
 *   A single search result, parsed directly from USA Search response JSON.
 *
 * @param string $module
 *   The drupal module executing the search.
 *
 * @return array
 *   A search result to be passed to Drupal's search-result.tpl.php.
 */
function usasearch_images_result_images($result, $module) {
  $protocol = isset($_SERVER['HTTPS']) ? 'https://' : 'http://';

  return array(
    'title' => usasearch_api_replace_unicode_char($result['title']),
    'link' => $protocol . $result['display_url'],
    'module' => $module,
    'thumbnail' => $result['thumbnail'],
    'image_url' => $result['media_url'],
    'snippet' => "<img src=\"{$result['thumbnail']['url']}\" class=\"thumbnail\" />",
    'extra' => array(
      'content_type' => $result['content_type'],
      'file_size' => format_size($result['file_size']),
      'dimensions' => $result['width'] . 'x' . $result['height'] . 'px',
    ),
    'type' => 'image',
  );
}
