<?php

/**
 * @file
 * Provides image search for the USA Search module.
 */

/**
 * Implements hook_search_info().
 */
function usasearch_images_search_info() {
  return array(
    'title' => 'Images',
    'path' => 'images',
    'conditions_callback' => 'usasearch_api_conditions',
  );
}

/**
 * Implements hook_search_execute().
 */
function usasearch_images_search_execute($keys = NULL, $conditions = array()) {
  $conditions['index'] = 'images';
  $module = 'usasearch_images';
  $results = usasearch_api_get_results($keys, $conditions, $module);

  return $results;
}
