<?php

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function digitalgov_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'digitalgov_search.help':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the help docs for DigitalGov Search, see <a href="!digitalgov-search-module">the online documentation</a></p>');
      return $output;
    break;
  }
}


//TODO: can I set the querystring params from search block in this preprocess??
/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
// function search_preprocess_block(&$variables) {
//   if ($variables['plugin_id'] == 'search_form_block') {
//     $variables['attributes']['role'] = 'search';
//   }
// }


//TODO: look into the hook_theme_suggestions_alter() in D8 to set the block template
//block_digitalgov_search_search_block

