<?php

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function usasearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'usasearch.help':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the help docs for DigitalGov Search, see <a href="!usasearch-module">the online documentation</a></p>');
      return $output;
    break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * alter the block search form so that drupal's token attributes are not passed
 * to the action as querystring params
 *
 * @see \Drupal\usasearch\Form\SearchBlockForm::buildForm()
 */
function usasearch_form_usasearch_search_block_form_alter(&$form, FormStateInterface $form_state) {
    $form['#token'] = FALSE;
    $form['form_id']['#access'] = FALSE;
    $form['form_build_id']['#access'] = FALSE;
    $form['form_token']['#access'] = FALSE;
}
