<?php
/**
 * @file
 * Replaces Drupal search, redirects all search queries to USASearch service (http://search.usa.gov).
 */

/**
 * System settings form for USASearch.
 */
function usasearch_admin() {
  $form = array();

  $form['usasearch_affiliate_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Affiliate name'),
    '#default_value' => variable_get('usasearch_affiliate_name', ''),
    '#size' => 30,
    '#maxlength' => 30,
    '#description' => t('Please enter your affiliate name provided by <a href="@usasearch_affiliates_url">USASearch</a>, eg. "example.gov".', array('@usasearch_affiliates_url' => url('https://search.usa.gov/affiliates'))),
    '#required' => TRUE,
  );
  $form['usasearch_action_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Search domain'),
    '#default_value' => variable_get('usasearch_action_domain', 'search.usa.gov'),
    '#size' => 30,
    '#maxlength' => 50,
    '#description' => t('You may enter a custom search domain, eg. "search.commerce.gov", or leave the default "search.usa.gov". This will change the search form action to submit search requests to the search domain entered. <strong>NOTE: Only change this if USASearch has configured this option for your search affiliate!</strong>'),
    '#required' => FALSE,
  );
  $form['usasearch_search_page'] = array(
    '#type' => 'checkbox',
    '#title' => t('Keep Drupal search page'),
    '#default_value' => variable_get('usasearch_search_page', 0),
    '#description' => t("To make best use of the USASearch module on your site the 'Search box' option should be enabled in the <a href='@usasearch_theme_settings'>global theme settings</a> or in your default theme settings or the search block placed on your site. Check this option if you want to keep the Drupal search page instead of redirecting this to USASearch. If you do neither of these the USASearch module won't be of much use. <strong>NOTE: You must clear your menu cache if you enable this setting.</strong>", array('@usasearch_theme_settings' => url('admin/build/themes/settings'))),
    '#required' => FALSE,
  );
  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_page().
 * To output required javascript and css references.
 */
function usasearch_preprocess_page(&$variables) {
  // Declare the variable
  $inline_js = '';
  // Check for usasearch_affiliate_name variable, if set output javascript and css references.
  // Detailed info about this USASearch feature here: http://usasearch.howto.gov/post/18861028503/how-to-add-our-code-to-your-website.
  if (variable_get('usasearch_affiliate_name', '')) {
    $affiliate_name = variable_get('usasearch_affiliate_name', '') ? check_plain(variable_get('usasearch_affiliate_name', '')) : '';
    $action_domain = check_plain(variable_get('usasearch_action_domain', 'search.usa.gov'));

    $inline_js .= "var usasearch_config = { siteHandle:'$affiliate_name' };\n";
    if ($action_domain != 'search.usa.gov') {
      $inline_js .= "usasearch_config['host'] = '//$action_domain'\n";
    }
    $inline_js .= "var script = document.createElement('script');\n";
    $inline_js .= "script.type = 'text/javascript';\n";
    $inline_js .= "script.src = '//$action_domain/javascripts/remote.loader.js';\n";
    $inline_js .= "document.getElementsByTagName('head')[0].appendChild(script);\n";
  }
  // Output contents of $inline_js into one combined inline javascript tag using drupal_add_js function.
  drupal_add_js($inline_js, 'inline');
}

/**
 * Page callback function to redirect requests to usasearch.
 */
function usasearch_redirect_to_usasearch($query = '') {
  // Set action_domain from variables table or default to search.usa.gov.
  $action_domain = check_plain(variable_get('usasearch_action_domain', 'search.usa.gov'));
  // Set affiliate_name from variables table, checking for a value using ternary operator.
  $affiliate_name = variable_get('usasearch_affiliate_name', '') ? check_plain(variable_get('usasearch_affiliate_name', '')) : '';
  // Set action_protocol from server globals, checking for a value using ternary operator.
  $action_protocol = isset($_SERVER['HTTPS']) ? 'https' : 'http';
  // Check for query terms and use them in redirect if there.
  if ($query) {
    drupal_goto("$action_protocol://$action_domain/search", array('query' => array('query' => filter_xss($query), 'affiliate' => $affiliate_name)));
  }
  else {
    drupal_goto("$action_protocol://$action_domain/search", array('query' => array('affiliate' => $affiliate_name)));
  }
}

/**
 * Implements hook_menu().
 * Adds admin screen under settings.
 */
function usasearch_menu() {
  $items = array();

  $items['admin/config/search/usasearch'] = array(
    'title' => 'USASearch settings',
    'description' => 'Contains settings for customizing site search to use USASearch',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usasearch_admin'),
    'access arguments' => array('administer search'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 * Point /search and /search/node/% paths to callback which redirects to usasearch.
 */
function usasearch_menu_alter(&$items) {
  if (!variable_get('usasearch_search_page', 0)) {
    $items['search'] = array(
      'access arguments' => array('search content'),
      'description' => 'Search Results',
      'page callback' => 'usasearch_redirect_to_usasearch',
      'type' => MENU_CALLBACK,
    );

    $items['search/node/%'] = array(
      'access arguments' => array('search content'),
      'description' => 'Search Results',
      'page callback' => 'usasearch_redirect_to_usasearch',
      'page arguments' => array(2),
      'type' => MENU_CALLBACK,
    );
  }
}

/**
 * Implements hook_form_alter().
 * Changes elements in the search block, search theme form, search page form.
 */
function usasearch_form_alter(&$form, &$form_state, $form_id) {
  // Search block and search box have similar form structure.
  if ($form_id == 'search_block_form' || $form_id == 'search_theme_form' || $form_id == 'search_form') {
    // Set action method, location and read affiliate from variable.
    $form['#method'] = 'get';
    $form['#action'] = '//' . check_plain(variable_get('usasearch_action_domain', 'search.usa.gov')) . '/search';
    // Check for affiliate_name variable before printing the affiliate form element.
    if ($affiliate_name = check_plain(variable_get('usasearch_affiliate_name', ''))) {
      $form['affiliate'] = array('#type' => 'hidden', '#value' => $affiliate_name);
    }
    // Remove unnecessary, hidden input fields.
    unset($form['form_build_id']);
    unset($form['form_token']);
    unset($form['form_id']);

    if ($form_id == 'search_form') {
      // Change text field name to query and unset advanced search in search_form.
      $form['basic']['inline']['keys']['#name'] = 'query';
      unset($form['advanced']);
      // Add autocomplete classes and set autocomplete HTML attribute to off on text field for type-ahead feature.
      if (variable_get('usasearch_affiliate_name', '')) {
        $form['basic']['inline']['keys']['#attributes'] = array('class' => array('usagov-search-autocomplete', 'ui-autocomplete-input', 'ui-corner-all'), 'autocomplete' => 'off');
      }
    }
    else {
      // Change text field name to query and title in search_block_form and search_theme_form.
      $form[$form_id]['#name'] = 'query';
      $form[$form_id]['#title'] = t('Search using USASearch');
      // Add autocomplete classes and set autocomplete HTML attribute to off on text field for type-ahead feature.
      if (variable_get('usasearch_affiliate_name', '')) {
        $form[$form_id]['#attributes'] = array('class' => array('usagov-search-autocomplete', 'ui-autocomplete-input', 'ui-corner-all'), 'autocomplete' => 'off');
      }
    }
  }
}
