<?php
/**
 * @file
 * Install, update and uninstall functions for the usasearch module.
 */

/**
 * Implements hook_update_N().
 */
function usasearch_update_1() {
  variable_del('usasearch_affiliate_id');
  variable_del('usasearch_discovery_tag');
}

/**
 * Implements hook_uninstall().
 */
function usasearch_uninstall() {
  variable_del('usasearch_affiliate_name');
  variable_del('usasearch_action_domain');
  variable_del('usasearch_search_page');
}
