<?php

/**
 * @file
 * Provides a USASearch box field, permitting searching of unique affliate.
 */

/**
 * Implements hook_usasearch_api_conditions().
 */
function usasearch_field_usasearch_api_conditions_alter(&$conditions) {
  if (!empty($_REQUEST['affiliate'])) {
    $conditions['affiliate'] = check_plain($_REQUEST['affiliate']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modify admin form to permit entry of possible affiliate ids.
 */
function usasearch_field_form_usasearch_admin_alter(&$form, &$form_state, $form_id) {
  $form['usasearch_field_affiliates'] = array(
    '#type' => 'textarea',
    '#title' => t('Allowed Affliate IDs'),
    '#description' => t('A pipe-delimited list of affiliate ids that may be used in the USASearch field, in the form of "affiliate_id|Title"'),
    '#default_value' => variable_get('usasearch_field_affiliates', ''),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modify the search form so that it contains a hidden affiliate id value.
 */
function usasearch_field_form_search_form_alter(&$form, &$form_state, $form_id) {
  $params = drupal_get_query_parameters();
  $form['affiliate'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($params['affiliate']) ? check_plain($params['affiliate']) : '',
  );
  $form['#validate'][] = 'usasearch_field_search_form_validate';
}

/**
 * Validation handler for search_form.
 */
function usasearch_field_search_form_validate(&$form, &$form_state) {
  if (!empty($form_state['values']['affiliate'])) {
    $affiliate = check_plain($form_state['values']['affiliate']);
    module_load_include('inc', 'usasearch_subsites');
    if (usasearch_field_is_affiliate($affiliate)) {
      // Add value to $form_state['conditions'], which will be used to
      // set the form destination in usasearch_api_search_form_submit().
      $form_state['conditions']['affiliate'] = $form_state['values']['affiliate'];
    }
  }
}

/**
 * Implements hook_field_info().
 */
function usasearch_field_field_info() {
  return array(
    'usasearch_field_affiliate' => array(
      'label' => t('USASearch'),
      'default_widget' => 'usasearch_field_affiliate_widget',
      'default_formatter' => 'usasearch_field_affiliate_formatter',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function usasearch_field_field_widget_info() {
  return array(
    'usasearch_field_affiliate_widget' => array(
      'label' => t('Affiliate ID'),
      'field types' => array('usasearch_field_affiliate'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function usasearch_field_field_formatter_info() {
  return array(
    'usasearch_field_affiliate_formatter' => array(
      'label' => t('Form'),
      'field types' => array('usasearch_field_affiliate'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function usasearch_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $value = isset($items[$delta]['usasearch_field_affiliate']) ? $items[$delta]['usasearch_field_affiliate'] : '';
  $widget = $element;

  switch ($instance['widget']['type']) {
    case 'usasearch_field_affiliate_widget':
      $widget += array(
        '#type' => 'select',
        '#title' => t('Available USASearch Affiliate IDs'),
        '#options' => usasearch_field_affiliates_list(),
        '#default_value' => $value,
        '#required' => 1,
      );
      break;
  }
  $element['usasearch_field_affiliate'] = $widget;

  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function usasearch_field_field_is_empty($item, $field) {
  return empty($item['usasearch_field_affiliate']);
}

/**
 * Implements hook_field_formatter_view().
 */
function usasearch_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();
  switch ($display['type']) {
    case 'usasearch_field_affiliate_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'form',
        );
        module_load_include('inc', 'search', 'search.pages');
        $form = drupal_get_form('search_form');
        $form['affiliate']['#value'] = $item['usasearch_field_affiliate'];
        unset($form['advanced']);
        array_push($element[$delta], $form);
      }
      break;
  }
  return $element;
}


/**
 * Returns an array of subsites.
 *
 * @return array
 *   The available subsites.
 */
function usasearch_field_affiliates_list() {
  $subsites_string = variable_get('usasearch_field_affiliates', '');

  module_load_include('module', 'list');
  $subsites = list_extract_allowed_values($subsites_string, 'list text', FALSE);

  return $subsites;
}

/**
 * Generates a list of subsite links.
 *
 * @return array
 *   A renderable array of subsite links.
 */
function usasearch_field_affiliate_links() {
  $subsites = usasearch_field_affiliates_list();

  $params = drupal_get_query_parameters();
  $subsite_links = array();
  foreach ($subsites as $affiliate_id => $subsite_name) {
    $query = array_merge($params, array('affiliate' => check_plain($affiliate_id)));
    $subsite_links[$affiliate_id] = l(t('@subsite_name', array('@subsite_name' => $subsite_name)), current_path(), array('query' => $query));
  }

  $markup = array(
    '#items' => $subsite_links,
    '#theme' => 'item_list',
  );

  return $markup;
}

/**
 * Verifies that a given subsite is in list of configured subsites.
 *
 * @param string $affiliate_id
 *
 * @return bool
 *   TRUE if the given subsite is in the list of configured subsites.
 */
function usasearch_field_is_affiliate($affiliate_id) {
  $subsites = usasearch_field_affiliates_list();

  return array_key_exists($affiliate_id, $subsites);
}

/**
 * Implements hook_block_info().
 */
function usasearch_field_block_info() {
  // This block displays a <ul> of links to subsite search pages.
  $blocks['usasearch_subsites'] = array(
    'info' => t('USASearch: Subsites'),
    'pages' => 'search/*',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usasearch_field_block_view($delta = '') {
  switch ($delta) {
    case 'usasearch_affiliates':
      $block['subject'] = t('Affiliates');

      module_load_include('inc', 'usasearch_affiliates');
      $block['content'] = usasearch_field_affiliate_links();
      break;
  }
  return $block;
}
