<?php

/**
 * @file
 * Provides a USASearch box field, permitting searching of unique affliate.
 */

/**
 * Implements hook_field_info().
 */
function usasearch_field_field_info() {
  return array(
    'usasearch_field_affiliate' => array(
      'label' => t('USASearch'),
      'default_widget' => 'usasearch_field_affiliate_widget',
      'default_formatter' => 'usasearch_field_affiliate_formatter',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function usasearch_field_field_widget_info() {
  return array(
    'usasearch_field_affiliate_widget' => array(
      'label' => t('Affiliate ID'),
      'field types' => array('usasearch_field_affiliate'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function usasearch_field_field_formatter_info() {
  return array(
    'usasearch_field_affiliate_formatter' => array(
      'label' => t('Form'),
      'field types' => array('usasearch_field_affiliate'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function usasearch_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $value = isset($items[$delta]['usasearch_field_affiliate']) ? $items[$delta]['usasearch_field_affiliate'] : '';
  $widget = $element;

  switch ($instance['widget']['type']) {
    case 'usasearch_field_affiliate_widget':
      module_load_include('inc', 'usasearch_api');
      $widget += array(
        '#type' => 'select',
        '#title' => t('Available USASearch Affiliate IDs'),
        '#options' => usasearch_api_affiliates_list(),
        '#default_value' => $value,
        '#required' => 1,
      );
      break;
  }
  $element['usasearch_field_affiliate'] = $widget;

  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function usasearch_field_field_is_empty($item, $field) {
  return empty($item['usasearch_field_affiliate']);
}

/**
 * Implements hook_field_formatter_view().
 */
function usasearch_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();
  switch ($display['type']) {
    case 'usasearch_field_affiliate_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'form',
        );
        module_load_include('inc', 'search', 'search.pages');
        $form = drupal_get_form('search_form');
        $form['affiliate']['#value'] = $item['usasearch_field_affiliate'];
        unset($form['advanced']);
        unset($form['basic']['keys']['#title']);
        array_push($element[$delta], $form);
      }
      break;
  }
  return $element;
}
