<?php

/**
 * @file
 * Provides image search for the USA Search module.
 */

/**
 * Implements hook_search_info().
 */
function usasearch_docs_search_info() {
  return array(
    'title' => 'Docs',
    'path' => 'docs',
    'conditions_callback' => 'usasearch_api_conditions',
  );
}

/**
 * Implements hook_usasearch_api_conditions().
 */
function usasearch_docs_usasearch_api_conditions_alter(&$conditions) {
  if (!empty($_REQUEST['dc'])) {
    $conditions['dc'] = check_plain($_REQUEST['dc']);
  }
}

/**
 * Implements hook_search_execute().
 */
function usasearch_docs_search_execute($keys = NULL, $conditions = array()) {
  module_load_include('inc', 'usasearch_api');
  $conditions['index'] = 'docs';
  $module = 'usasearch_docs';
  $results = usasearch_api_get_results($keys, $conditions, $module);

  return $results;
}

/**
 * Converts a USA Search result to a Drupal search result for doc index.
 *
 * @param array $result
 *   A single search result, parsed directly from USA Search response JSON.
 *
 * @param string $module
 *   The drupal module executing the search.
 *
 * @return array
 *   A search result to be passed to Drupal's search-result.tpl.php.
 */
function usasearch_docs_result_docs($result, $module) {
  return array(
    'title' => usasearch_api_replace_unicode_char($result['title']),
    'link' => $result['unescapedUrl'],
    'snippet' => usasearch_api_replace_unicode_char($result['content']),
    'module' => $module,
    'date' => usasearch_api_utc_to_unix_timestamp($result['publishedAt']),
    'type' => 'docs',
  );
}

/**
 * Implements hook_form_alter().
 */
function usasearch_docs_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_form' && $form['module']['#value'] == 'usasearch_docs') {
    // The 'dc' element to specific document collections.
    $form['dc'] = array(
      '#type' => 'select',
      '#title' => t('Collection'),
      // @todo Replace this with values derived from an admin variable.
      '#options' => array('' => 'none', 'test' => 'test'),
      '#default_value' => isset($_GET['dc']) ? check_plain($_GET['dc']) : 'none',
    );

    $form['#validate'][] = 'usasearch_docs_search_form_validate';
  }
}

/**
 * Validation handler for search_form.
 */
function usasearch_docs_search_form_validate(&$form, &$form_state) {
  if (!empty($form_state['values']['dc'])) {
    // Add value to $form_state['conditions'], which will be used to
    // set the form destination in usasearch_api_search_form_submit().
    $form_state['conditions']['dc'] = $form_state['values']['dc'];
  }
}
