<?php

/**
 * @file
 * Provides image search for the USA Search module.
 */

/**
 * Implements hook_search_info().
 */
function usasearch_docs_search_info() {
  return array(
    'title' => 'Docs',
    'path' => 'docs',
    'conditions_callback' => 'usasearch_api_conditions',
  );
}

/**
 * Implements hook_search_execute().
 */
function usasearch_docs_search_execute($keys = NULL, $conditions = array()) {
  $conditions['index'] = 'docs';
  $module = 'usasearch_docs';
  $results = usasearch_api_get_results($keys, $conditions, $module);

  return $results;
}

/**
 * Converts a USA Search result to a Drupal search result for docs index.
 *
 * @param $result
 * @param $module
 * @return array
 */
function usasearch_docs_result_docs($result, $module) {
  return array(
    'title' => usasearch_api_replace_unicode_char($result['title']),
    'link' => $result['unescapedUrl'],
    'snippet' => usasearch_api_replace_unicode_char($result['content']),
    'module' => $module,
    'date' => $result['publishedAt'],
    'type' => 'docs',
  );
}
