<?php

/**
 * @file
 * Allows multiple affiliate ids to be searched.
 */

/**
 * Implements hook_entity_info_alter().
 *
 * Defines the usasearch bundle for fieldable panels panes.
 */
function usasearch_subsites_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['usasearch'] = array(
    'label' => t('USASearch'),
    'pane category' => t('Fielded panes'),
    'pane top level' => FALSE,
    // 'pane icon' => '/path/to/custom/icon/for/this/pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/usasearch',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_field_extra_fields_alter().
 */
function usasearch_subsites_field_extra_fields_alter(&$info) {
  $entity_type = 'fieldable_panels_pane';
  $bundle = 'usasearch';
  if (isset($info[$entity_type])) {
    $entity_info = entity_get_info($entity_type);
      if (isset($info[$entity_type][$bundle]['form'])) {
        $info[$entity_type][$bundle]['form']['affiliate'] = array(
          'label' => t('Affiliate ID'),
          'description' => t('Affiliate ID'),
          'weight' => -4,
        );
      }
      if (isset($info[$entity_type][$bundle]['display'])) {
        $info[$entity_type][$bundle]['display']['search'] = array(
          'label' => t('Search Box'),
          'description' => t('Search Box'),
          'weight' => 0,
        );
      }

  }
}

/**
 * Implements hook_usasearch_api_conditions().
 */
function usasearch_subsites_usasearch_api_conditions_alter(&$conditions) {
  if (!empty($_REQUEST['affiliate'])) {
    $conditions['affiliate'] = check_plain($_REQUEST['affiliate']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modify admin form to permit entry of possible affiliate ids.
 */
function usasearch_subsites_form_usasearch_admin_alter(&$form, &$form_state, $form_id) {
  $form['usasearch_subsite_affiliate_ids'] = array(
    '#type' => 'textarea',
    '#title' => t('Subsite Affliate IDs'),
    '#description' => t('A pipe-delimited list of subsite affiliate ids, in the form of "affiliate_id|Subsite Name"'),
    '#default_value' => variable_get('usasearch_subsite_affiliate_ids', ''),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modify the search form so that it contains a hidden affiliate id value.
 */
function usasearch_subsites_form_search_form_alter(&$form, &$form_state, $form_id) {
  $params = drupal_get_query_parameters();
  $form['affiliate'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($params['affiliate']) ? check_plain($params['affiliate']) : '',
  );
  $form['#validate'][] = 'usasearch_subsites_search_form_validate';
}

/**
 * Validation handler for search_form.
 */
function usasearch_subsites_search_form_validate(&$form, &$form_state) {
  if (!empty($form_state['values']['affiliate'])) {
    $affiliate = check_plain($form_state['values']['affiliate']);
    module_load_include('inc', 'usasearch_subsites');
    if (usasearch_subsites_is_subsite($affiliate)) {
      // Add value to $form_state['conditions'], which will be used to
      // set the form destination in usasearch_api_search_form_submit().
      $form_state['conditions']['affiliate'] = $form_state['values']['affiliate'];
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Modifies fieldable panels pane form to allow entry of an affiliate id
 * per entity.
 */
function usasearch_subsites_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form':
    case 'fieldable_panels_panes_entity_edit_form':

      $extra_fields = field_info_extra_fields('fieldable_panels_pane', 'usasearch', 'form');
      if ($form['#bundle'] == 'usasearch') {
        module_load_include('inc', 'usasearch_subsites');
        $settings = isset($form_state['entity']->settings) ? (array) unserialize($form_state['entity']->settings) : array();
        $form['affiliate'] = array(
          '#type' => 'select',
          '#title' => $extra_fields['affiliate']['label'],
          '#description' => $extra_fields['affiliate']['description'],
          '#options' => usasearch_subsites_list(),
          '#required' => TRUE,
          '#default_value' => isset($settings['usasearch_affiliate']) ? check_plain($settings['usasearch_affiliate']) : '',
          '#weight' => $extra_fields['affiliate']['weight'],
        );

        $form['#validate'][] = 'usasearch_subsites_fpp_validate';
        array_unshift($form['#submit'], 'usasearch_subsites_fpp_submit');
      }
      break;
  }
}

/**
 * Validation callback for fieldable_panels_panes_entity_edit_form.
 */
function usasearch_subsites_fpp_validate(&$form, &$form_state) {
  module_load_include('inc', 'usasearch_subsites');
  if (!usasearch_subsites_is_subsite(check_plain($form_state['values']['affiliate']))) {
    form_set_error('affiliate', t('Affiliate ID is not in list of permitted IDs.'));
  }
}

/**
 * Submit callback for fieldable_panels_panes_entity_edit_form.
 */
function usasearch_subsites_fpp_submit(&$form, &$form_state) {
  $settings = isset($form_state['entity']->settings) ? (array) unserialize($form_state['entity']->settings) : array();
  $settings['usasearch_affiliate'] = $form_state['values']['affiliate'];
  $form_state['entity']->settings = serialize($settings);
}

/**
 * Implements hook_block_info().
 */
function usasearch_subsites_block_info() {
  // This block displays a <ul> of links to subsite search pages.
  $blocks['usasearch_subsites'] = array(
    'info' => t('USASearch: Subsites'),
    'pages' => 'search/*',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usasearch_subsites_block_view($delta = '') {
  switch ($delta) {
    case 'usasearch_subsites':
      $block['subject'] = t('Subsites');

      module_load_include('inc', 'usasearch_subsites');
      $block['content'] = usasearch_subsites_links();
      break;
  }
  return $block;
}

/**
 * Implements hook_entity_view().
 */
function usasearch_subsites_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'fieldable_panels_pane' && $entity->bundle == 'usasearch') {
    $extra_fields = field_info_extra_fields('fieldable_panels_pane', 'usasearch', 'display');
    $form = drupal_get_form('search_form');
    $form['affiliate']['#value'] = $settings = isset($entity->settings) ? (array) unserialize($entity->settings) : array();
    $form['#weight'] = $extra_fields['search']['display'][$view_mode]['weight'];
    unset($form['advanced']);
    $entity->content['search'] = $form;
  }
}
