<?php

/**
 * @file
 * USA Search hosted search.
 */

/**
 * Implements hook_menu_alter().
 */
function usasearch_hosted_menu_alter(&$items) {
  $items['search'] = array(
    'access arguments' => array('search content'),
    'description' => 'Search Results',
    'page callback' => 'usasearch_hosted_redirect',
    'type' => MENU_CALLBACK,
    'file' => drupal_get_path('module', 'usasearch_hosted') . '/usasearch_hosted.inc',
  );
  $items['search/*'] = array(
    'access arguments' => array('search content'),
    'description' => 'Search Results',
    'page callback' => 'usasearch_hosted_redirect',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => drupal_get_path('module', 'usasearch_hosted') . '/usasearch_hosted.inc',
  );
}

/**
 * Implements hook_form_alter().
 *
 * Changes elements in the search block, search theme form, search page form.
 */
function usasearch_hosted_form_alter(&$form, &$form_state, $form_id) {

  // Search block and search box have similar form structure.
  if ($form_id == 'search_block_form'
    || $form_id == 'search_theme_form'
    || $form_id == 'search_form'
    || strpos($form_id, 'usasearch_field_search_box_') !== FALSE) {
    $action_domain = check_plain(variable_get('usasearch_action_domain', 'http://search.usa.gov'));
    $affiliate_name = check_plain(variable_get('usasearch_affiliate_name', ''));

    // Set action method, location and read affiliate from variable.
    $form['#method'] = 'get';
    $form['#action'] = $action_domain . '/search';

    $form['affiliate']['#type'] = 'hidden';
    // Check for affiliate_name variable before printing the affiliate form
    // element. We also first check that usasearch_field has not already set
    // the affiliate.
    if ($affiliate_name && empty($form['affiliate']['#value'])) {
      $form['affiliate']['#value'] = $affiliate_name;
    }

    // Remove unnecessary, hidden input fields.
    unset($form['form_build_id']);
    unset($form['form_token']);
    unset($form['form_id']);

    if ($form_id == 'search_form') {
      // Change text field name to query.
      $form['basic']['keys']['#attributes']['name'] = 'query';
      // Unset 'advanced' fieldset.
      unset($form['advanced']);
    }
    else {
      // Change text field name to query.
      $form[$form_id]['#attributes']['name'] = 'query';
    }
  }
}
