<?php

/**
 * @file
 * Provides an index of site content to USA Search.
 */

/**
 * Implements hook_services_resources().
 */
function usasearch_index_services_resources() {
  $resources = array(
    'usasearch' => array(
      'index' => array(
        'file' => array(
          'type' => 'inc',
          'module' => 'usasearch_index',
          'name' => 'usasearch_index',
        ),
        'callback' => '_usasearch_index_resource',
        'args' => array(
          array(
            'name' => 'page',
            'optional' => TRUE,
            'type' => 'int',
            'description' => 'The zero-based index of the page to get, defaults to 0.',
            'default value' => 0,
            'source' => array('param' => 'page'),
          ),
          array(
            'name' => 'pagesize',
            'optional' => TRUE,
            'type' => 'int',
            'description' => 'Number of records to get per page.',
            'default value' => variable_get('services_node_index_page_size', 20),
            'source' => array('param' => 'pagesize'),
          ),
        ),
        'access arguments' => array('access content'),
      ),
    ),
  );

  return $resources;
}
